# Generated by Django 2.0.6 on 2018-10-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_vote_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='vote',
            field=models.BooleanField(default=False),
        ),
    ]
