# Generated by Django 2.0.6 on 2018-10-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_student_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vote',
            field=models.BooleanField(default=False),
        ),
    ]
