# Generated by Django 2.0.6 on 2018-10-19 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_user_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='vote',
        ),
    ]
