# Generated by Django 2.0.6 on 2018-10-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_remove_student_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
