# Generated by Django 2.0.6 on 2018-10-19 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_vote_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='', max_length=500)),
                ('desc', models.CharField(default='', max_length=10000)),
                ('file_upload', models.FileField(upload_to='private_files/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
