# Generated by Django 2.0.6 on 2018-10-19 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_myfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfiles',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='classroom.Student'),
        ),
    ]
