# Generated by Django 2.0.6 on 2018-10-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='totalclasses',
            field=models.IntegerField(default=0),
        ),
    ]
