# Generated by Django 2.0.6 on 2018-10-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_course_totalclasses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classestaken',
            field=models.IntegerField(default=0),
        ),
    ]
